default:
  enabled: true
  gbif: true
  metadata:
    title: long_name
    description: description
    dataLanguage: language
    license: intellectual_rights
  fields:
  - occurrenceID
  - basisOfRecord
  - taxonID
  - scientificName
  - taxonRank
  - kingdom
  - occurrenceStatus
  - individualCount
  - lifeStage
  - sex
  - eventDate
  - decimalLatitude
  - decimalLongitude
  - geodeticDatum
  - coordinateUncertaintyInMeters
  - footprintWKT
  - footprintSRS
  - locality
  - county
  - stateProvince
  - higherGeography
  - country
  - recordedBy
  - identifiedBy
  - associatedMedia
  - dcterms:license
  - dcterms:bibliographicCitation
  - occurrenceRemarks
  - eventRemarks
  nmax: 2.5e4
  filters:
    abundance_min: 0
    record_quality: ["expert_verified", "community_verified", "unassessed"]
    requires_verification: false

HR.447:
  enabled: true
  filters:
    date_range_ymd: ["2015-01-01", ""]
