default:
  enabled: false
  gbif: false
  metadata:
    type: type
    title: long_name
    description: description
    language: metadata_language
    license: intellectual_rights
  eml:
    dataLanguage: language
    methods: methods
    geographicDescription: geographic_coverage
    contact: person_responsible
    email: contact_email
  fields:
  - occurrenceID
  - basisOfRecord
  - taxonID
  - scientificName
  - taxonRank
  - kingdom
  - occurrenceStatus
  - individualCount
  - lifeStage
  - sex
  - eventDate
  - decimalLatitude
  - decimalLongitude
  - geodeticDatum
  - coordinateUncertaintyInMeters
  - footprintWKT
  - footprintSRS
  - locality
  - county
  - stateProvince
  - higherGeography
  - country
  - recordedBy
  - identifiedBy
  - associatedMedia
  - dcterms:license
  - dcterms:bibliographicCitation
  - occurrenceRemarks
  - eventRemarks
  nmax: 2.5e4
  filters:
    abundance_min: 0
    record_quality: ["expert_verified", "community_verified", "unassessed"]
    requires_verification: false

HR.89:
  enabled: true
  gbif: false

HR.48:
  enabled: false
  gbif: false
