default:
  enabled: true
  metadata:
    title: long_name
    description: description
    language: language
    license: intellectual_rights
  fields:
  - occurrenceID
  - basisOfRecord
  - eventDate
  - country
  - footprintWKT
  - geodeticDatum
  - coordinateUncertaintyInMeters
  - kingdom
  - scientificName
  - taxonRank
  nmax: 2.5e4
  filters:

HR.447:
  filters:
    date_range_ymd: ["2015-01-01", ""]
