default:
  enabled: false
  gbif: false
  timeout: 10
  max_age_weeks: 1
  metadata:
    type: type
    title: long_name
    description: description
    language: metadata_language
    license: intellectual_rights
  eml:
    dataLanguage: language
    methods: methods
    geographicDescription: geographic_coverage
    contact: person_responsible
    email: contact_email
  fields:
  - occurrenceID
  - catalogNumber
  - institutionCode
  - collectionCode
  - basisOfRecord
  - taxonID
  - taxonConceptID
  - scientificName
  - taxonRank
  - kingdom
  - verbatimIdentification
  - occurrenceStatus
  - individualCount
  - lifeStage
  - sex
  - typeStatus
  - eventID
  - eventDate
  - decimalLatitude
  - decimalLongitude
  - geodeticDatum
  - coordinateUncertaintyInMeters
  - footprintWKT
  - footprintSRS
  - locality
  - county
  - stateProvince
  - higherGeography
  - country
  - recordedBy
  - identifiedBy
  - associatedMedia
  - dcterms:bibliographicCitation
  - occurrenceRemarks
  - eventRemarks
  nmax: 2.5e4
  filters:
    abundance_min: 0
    record_quality:
    - expert_verified
    - community_verified
    - unassessed
    requires_verification: false
  facts:
    recordNumber: MY.legID
    verbatimElevation: MY.alt
    habitat: MY.habitatDescription
    substrate: MY.substrate
    localityDescription: MY.localityDescription
  combine:
    habitat:
    - habitat
    - substrate
    locality:
    - locality
    - localityDescription
