default:
  enabled: false
  gbif: false
  timeout: 10
  max_age_weeks: 1
  metadata:
    type: type
    subtype: collection_type
    title: long_name
    abbreviation: abbreviation
    description: description
    homepage: online_url
    logoUrl: logo
    language: metadata_language
    license: intellectual_rights
  eml:
    dataLanguage: language
    methods: methods
    geographicDescription: geographic_coverage
    contact: person_responsible
    email: contact_email
    url: online_url
    datasetSubtype: collection_type
    creator: intellectual_owner
  fields:
  - occurrenceID
  - catalogNumber
  - recordNumber
  - institutionCode
  - collectionCode
  - basisOfRecord
  - materialEntityType
  - taxonConceptID
  - scientificName
  - taxonRank
  - kingdom
  - verbatimIdentification
  - occurrenceStatus
  - individualCount
  - organismQuantity
  - organismQuantityType
  - lifeStage
  - sex
  - typeStatus
  - eventID
  - eventDate
  - year
  - startDayOfYear
  - decimalLatitude
  - decimalLongitude
  - geodeticDatum
  - coordinateUncertaintyInMeters
  - footprintWKT
  - footprintSRS
  - verbatimElevation
  - locality
  - municipality
  - county
  - stateProvince
  - country
  - countryCode
  - higherGeography
  - continent
  - habitat
  - recordedBy
  - identifiedBy
  - dcterms:bibliographicCitation
  - occurrenceRemarks
  - eventRemarks
  - informationWithheld
  - dataGeneralizations
  - dcterms:modified
  - dcterms:license
  - associatedMedia
  nmax: 2.5e4
  filters:
    abundance_min: 0
    record_quality:
    - expert_verified
    - community_verified
    - unassessed
    requires_verification: false
  facts:
    recordNumber: MY.legID
    verbatimElevation: MY.alt
    habitat: MY.habitatDescription
    substrate: MY.substrate
    localityDescription: MY.localityDescription
  combine:
    habitat:
    - habitat
    - substrate
    locality:
    - locality
    - localityDescription
