default:
  enabled: true
  metadata:
    title: long_name
    description: description
    dataLanguage: language
    license: intellectual_rights
  fields:
  - occurrenceID
  - basisOfRecord
  - scientificName
  - taxonRank
  - kingdom
  - individualCount
  - eventDate
  - decimalLatitude
  - decimalLongitude
  - geodeticDatum
  - coordinateUncertaintyInMeters
  - footprintWKT
  - locality
  - county
  - stateProvince
  - higherGeography
  - country
  nmax: 2.5e4
  filters:

HR.447:
  filters:
    date_range_ymd: ["2015-01-01", ""]
