version: "3.7"

services:
  sut:
    build:
      context: .
    command: R --slave -e 'print(cv <- covr::package_coverage("f2g"), "functions"); covr::report(cv, file = "coverage/code-coverage.html", FALSE)'
    volumes:
      - ./cov:/home/user/coverage