services:
  f2g:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - var:/home/user/logs
      - archives:/home/user/archives

volumes:
  var:
  archives:
