kind: Template
apiVersion: v1
parameters:
  - name: APP
    required: true
    value: finbif2gbif
  - name: APP_TITLE
    required: true
    value: "FinBIF to GBIF"
  - name: APP_PORT
    required: true
    value: "8000"
  - name: HOME
    required: true
    value: /home/user
  - name: ARCHIVE
    required: true
    value: archives
  - name: HEALTH
    required: true
    value: healthz
  - name: LIVENESS_PERIOD
    required: true
    value: "30"
  - name: FAILURE_THRESHOLD
    required: true
    value: "5"
  - name: READINESS_PERIOD
    required: true
    value: "5"
  - name: LOG
    required: true
    value: log-monitor
  - name: LOG_PORT
    required: true
    value: "3838"
  - name: LOG_DIR
    required: true
    value: logs
  - name: LOG_HOST
    required: true
    value: log
  - name: GIT_HOST
    required: true
    value: https://github.com
  - name: ORG
    required: true
    value: luomus
  - name: PROD
    required: true
    value: main
  - name: DEV
    required: true
    value: dev
  - name: TAG
    required: true
    value: latest
  - name: STORAGE
    required: true
    value: "40Gi"
  - name: SMALL_STORAGE
    required: true
    value: "3Gi"
  - name: REPS
    required: true
    value: "1"
  - name: CRON
    required: true
    value: job
  - name: CRON_SCHEDULE
    required: true
    value: "0/30 * * * *"
  - name: CRON_CMD
    required: true
    value: '["Rscript", "finbif2gbif.R"]'
  - name: CRON_LIMIT
    required: true
    value: "3"
  - name: HOST
    required: true
  - name: FINBIF_ACCESS_TOKEN
    required: true
  - name: FINBIF_API
    required: true
  - name: DEV_FINBIF_ACCESS_TOKEN
    required: true
  - name: DEV_FINBIF_API
    required: true
  - name: GBIF_USER
    required: true
  - name: GBIF_ORG
    required: true
  - name: GBIF_INSTALLATION
    required: true
  - name: GBIF_PASS
    required: true
  - name: GBIF_API
    required: true
  - name: DEV_GBIF_ORG
    required: true
  - name: DEV_GBIF_INSTALLATION
    required: true
  - name: DEV_GBIF_PASS
    required: true
  - name: DEV_GBIF_API
    required: true
  - name: TIMEOUT
    required: true
  - name: GITHUB_SECRET
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{20}"
metadata:
  name: ${APP}
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP}:${TAG}
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${APP}.git
        ref: ${PROD}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${DEV}-${APP}:${TAG}
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${APP}.git
        ref: ${DEV}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${LOG}:${TAG}
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${LOG}.git
        ref: ${PROD}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${APP}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${APP}
      spec:
        containers:
        - image: ${APP}:${TAG}
          name: ${APP}
          ports:
          - containerPort: ${APP_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${LOG}
          - mountPath: ${HOME}/${ARCHIVE}
            name: ${APP}-${ARCHIVE}
          livenessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}
        volumes:
        - name: ${LOG}
          persistentVolumeClaim:
            claimName: ${LOG}
        - name: ${APP}-${ARCHIVE}
          persistentVolumeClaim:
            claimName: ${APP}-${ARCHIVE
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}
        from:
          kind: ImageStreamTag
          name: ${APP}:${TAG}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${APP}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${DEV}-${APP}
      spec:
        containers:
        - image: ${DEV}-${APP}:${TAG}
          name: ${DEV}-${APP}
          ports:
          - containerPort: ${APP_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${DEV}-${LOG}
          - mountPath: ${HOME}/${ARCHIVE}
            name: ${DEV}-${APP}-${ARCHIVE}
          livenessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}-${DEV}
          - name: BRANCH
            value: ${DEV}
        volumes:
        - name: ${DEV}-${LOG}
          persistentVolumeClaim:
            claimName: ${DEV}-${LOG}
        - name: ${DEV}-${APP}-${ARCHIVE}
          persistentVolumeClaim:
            claimName: ${DEV}-${APP}-${ARCHIVE}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${DEV}-${APP}
        from:
          kind: ImageStreamTag
          name: ${DEV}-${APP}:${TAG}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${LOG}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${LOG}
      spec:
        containers:
        - image: ${LOG}:${TAG}
          name: ${LOG}
          ports:
          - containerPort: ${LOG_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${LOG}
          livenessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}
        volumes:
        - name: ${LOG}
          persistentVolumeClaim:
            claimName: ${LOG}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${LOG}
        from:
          kind: ImageStreamTag
          name: ${LOG}:${TAG}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${LOG}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${DEV}-${LOG}
      spec:
        containers:
        - image: ${LOG}:${TAG}
          name: ${DEV}-${LOG}
          ports:
          - containerPort: ${LOG_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${DEV}-${LOG}
          livenessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}-${DEV}
        volumes:
        - name: ${DEV}-${LOG}
          persistentVolumeClaim:
            claimName: ${DEV}-${LOG}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${DEV}-${LOG}
        from:
          kind: ImageStreamTag
          name: ${LOG}:${TAG}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${LOG}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${SMALL_STORAGE}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${SMALL_STORAGE}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${APP}-${ARCHIVE}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${STORAGE}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}-${ARCHIVE}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${SMALL_STORAGE}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}-tcp
      port: ${APP_PORT}
      protocol: TCP
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${APP}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}-tcp
      port: ${APP_PORT}
      protocol: TCP
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${APP}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${LOG_PORT}-tcp
      port: ${LOG_PORT}
      protocol: TCP
      targetPort: ${{LOG_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${LOG}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${LOG_PORT}-tcp
      port: ${LOG_PORT}
      protocol: TCP
      targetPort: ${{LOG_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${LOG}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    host: ${HOST}
    port:
      targetPort: ${APP_PORT}-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP}
    wildcardPolicy: None
- kind: Route
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    host: ${DEV}-${HOST}
    port:
      targetPort: ${APP_PORT}-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${DEV}-${APP}
    wildcardPolicy: None
- kind: Route
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    host: ${LOG_HOST}-${HOST}
    port:
      targetPort: ${LOG_PORT}-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${LOG}
    wildcardPolicy: None
- kind: Route
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
    labels:
      app: ${APP}
  spec:
    host: ${DEV}-${LOG_HOST}-${HOST}
    port:
      targetPort: ${LOG_PORT}-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${DEV}-${LOG}
    wildcardPolicy: None
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: ${APP}
  spec:
    schedule: ${CRON_SCHEDULE}
    successfulJobsHistoryLimit: ${{CRON_LIMIT}}
    failedJobsHistoryLimit: ${{CRON_LIMIT}}
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              app: ${APP}
          spec:
            containers:
            - name: ${APP}-${CRON}
              image: ${APP}:${TAG}
              command: ${{CRON_CMD}}
              volumeMounts:
              - mountPath: ${HOME}/${ARCHIVE}
                name: ${DEV}-${APP}-${ARCHIVE}
              - mountPath: ${HOME}/${LOG_DIR}
                name: ${LOG}
              env:
              - name: ENDPOINTS
                value: https://${HOST}/${ARCHIVE}
              - name: TIMEOUT
                value: ${TIMEOUT}
              - name: FINBIF_ACCESS_TOKEN
                value: ${FINBIF_ACCESS_TOKEN}
              - name: FINBIF_API
                value: ${FINBIF_API}
              - name: GBIF_USER
                value: ${GBIF_USER}
              - name: GBIF_ORG
                value: ${GBIF_ORG}
              - name: GBIF_INSTALLATION
                value: ${GBIF_INSTALLATION}
              - name: GBIF_PASS
                value: ${GBIF_PASS}
              - name: GBIF_API
                value: ${GBIF_API}
            volumes:
            - name: ${APP}-${ARCHIVE}
              persistentVolumeClaim:
                claimName: ${APP}-${ARCHIVE}
            - name: ${LOG}
              persistentVolumeClaim:
                claimName: ${LOG}
            restartPolicy: Never
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: ${DEV}-${APP}
  spec:
    schedule: ${CRON_SCHEDULE}
    successfulJobsHistoryLimit: ${{CRON_LIMIT}}
    failedJobsHistoryLimit: ${{CRON_LIMIT}}
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              app: ${APP}
          spec:
            containers:
            - name: ${DEV}-${APP}-${CRON}
              image: ${DEV}-${APP}:${TAG}
              command: ${{CRON_CMD}}
              volumeMounts:
              - mountPath: ${HOME}/${ARCHIVE}
                name: ${DEV}-${APP}-${ARCHIVE}
              - mountPath: ${HOME}/${LOG_DIR}
                name: ${DEV}-${LOG}
              env:
              - name: BRANCH
                value: ${DEV}
              - name: ENDPOINTS
                value: https://${DEV}-${HOST}/${ARCHIVE}
              - name: TIMEOUT
                value: ${TIMEOUT}
              - name: FINBIF_ACCESS_TOKEN
                value: ${DEV_FINBIF_ACCESS_TOKEN}
              - name: FINBIF_API
                value: ${DEV_FINBIF_API}
              - name: GBIF_USER
                value: ${GBIF_USER}
              - name: GBIF_ORG
                value: ${DEV_GBIF_ORG}
              - name: GBIF_INSTALLATION
                value: ${DEV_GBIF_INSTALLATION}
              - name: GBIF_PASS
                value: ${DEV_GBIF_PASS}
              - name: GBIF_API
                value: ${DEV_GBIF_API}
            volumes:
            - name: ${DEV}-${APP}-${ARCHIVE}
              persistentVolumeClaim:
                claimName: ${DEV}-${APP}-${ARCHIVE}
            - name: ${DEV}-${LOG}
              persistentVolumeClaim:
                claimName: ${DEV}-${LOG}
            restartPolicy: Never
